### ISSUE TITLE
Wrong implementation of the Polygon shape type

### ISSUE THREAD

**Issue by Descharges** [twpayne/go-shapefile#13]
Hi there :D

When reading an `SHPRecord` from a shapefile with a Polygon (5) shape type, the geometry in the Geom field is a `geom.Polygon` with the rings copied-pasted from the file. However, the official shapefile documentation states that :

> A polygon consists of one or more rings. A ring is a connected sequence of four or more
points that form a closed, non-self-intersecting loop. A polygon may contain multiple
outer rings. The order of vertices or orientation for a ring indicates which side of the ring
is the interior of the polygon. The neighborhood to the right of an observer walking along
the ring in vertex order is the neighborhood inside the polygon. Vertices of rings defining
holes in polygons are in a counterclockwise direction. Vertices for a single, ringed
polygon are, therefore, always in clockwise order. The rings of a polygon are referred to
as its parts.

The output type for a Polygon record should actually be `geom.MultiPolygon`, with every outer ring (clockwise) as a Polygon, and every inner ring (counterclockwise) as a hole in the containing Polygon.

(Awesome implementation otherwise, which works well with your even more awesome go-geom package !)

**Comment by twpayne** [comment]
Thanks for spotting this and for the kind words. #15 should fix it.

**Comment by twpayne** [comment]
I've tagged `v0.0.3` which includes the fix.

**Comment by Descharges** [comment]
Works like a charm ! Thank you !
