### ISSUE TITLE
EOF

### ISSUE THREAD

**Issue by radi2015** [twpayne/go-shapefile#3]
shapefile, err := shapefile.ReadFS(os.DirFS("/Users/xxx/Downloads/tmp/data"), "bj", nil)
	if err != nil {
		fmt.Println(err)   //EOF
		return
	}
	fmt.Println(shapefile.SHP.ShapeType)

**Comment by twpayne** [comment]
There is not enough information in your comment to reproduce the problem.

**Comment by radi2015** [comment]
[bj2.zip](https://github.com/twpayne/go-shapefile/files/10370012/bj2.zip)
this is shapefile which i ziped 

shapefile.ReadFS(os.DirFS("/Users/shilulu/Downloads/tmp/docker/gdal"), "bj2", nil) // will be error

**Comment by radi2015** [comment]
```
func readFull(r io.Reader, data []byte) error {
	for {
		switch n, err := r.Read(data); {
		case errors.Is(err, io.EOF) && n == len(data):
			return nil
		case err != nil:
			return err
		case n == 0:
			return io.EOF
		case n < len(data):
			data = data[n:]
		default:
			return nil
		}
	}
}
```
for my file in this code
n, err := r.Read(data);  err is eof,  n=0, len(data)=1

next code is really need ? in fact my shapefile is ok, and can be loaded by qgis
```
	data := make([]byte, 1)
	if err := readFull(r, data); err != nil {
		return nil, err
	}
	if data[0] != '\x1a' {
		return nil, fmt.Errorf("%d: invalid end of file marker", data[0])
	}
```

**Comment by twpayne** [comment]
Thank you for the detail.

go-shapefile's parsing of `.dbf` files is based on [this description of the format](https://www.clicketyclick.dk/databases/xbase/format/dbf.html), which includes the `\x1a` as an end of file marker. That said, I've not found a proper specification of the `.dbf` format so I don't think go-shapefile needs to be strict about this.

I'll open a PR to make the end of file marker optional, which should fix this issue.
