### ISSUE TITLE
[feature]: Scanner Interface

### ISSUE THREAD

**Issue by TuSKan** [twpayne/go-shapefile#7]
Hi!
Thank you very much for this contribution.
This implementation is great! Simple and clean.
I was looking for shapefile package more integrated with your amazing package geom. 

I have make a fork and just code some draft of a scanner interface here:
https://github.com/TuSKan/go-shapefile/blob/scan/scanner.go

My files is really huge, so I need to care a lot of parallel processing and  of memory allocation.

I'm looking forward to see your comments and glad to do any modifications for a future PR.

**Comment by twpayne** [comment]
Thank you, this code looks very good indeed and please do open a PR so we can discuss details.

**Comment by TuSKan** [comment]
Please, take a look on [scanner.go](https://github.com/TuSKan/go-shapefile/blob/scan/scanner.go).
I did o lot o messy there to make it work for me, there is a lot of duplicated code with parts of the library that I avoid to change and I wrote a different shapefile type just to reproduce the tests.
Please, fell free to choose what make sense to your library and what you don't like to change. Just let me know, I can propose a PR based on that.

**Comment by TuSKan** [comment]
I have just included **cpg** files also for different encoding
And some go routines on scan for better performance

**Comment by twpayne** [comment]
Great! Please do open a PR for discussion.

**Comment by twpayne** [comment]
Fixed by @TuSKan in #8.
